language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - hhvm

env:
  matrix:
  - allow_failures:
      php: hhvm
  - secure: Z+aHwB7+nRmBZVdQ5S2dovXZak0a8S2qWIF57DDLIjKF/ag/jaX8SOGZ3Ka/ghclNb1BXnKD/g9Pfy6cLmXaWHLV03Oo+qzNOAPQGbelAuorddPIAyeL/rbUGz78tLhmofRUYCkv9fnt2BfDbiwY9w+1i2MwVdWHsNW4aXxTeoc=

before_script:
  - composer install

script: phpunit --configuration phpunit.xml --coverage-text
