language: php

php:
  - 5.3
  - 5.4
  - 5.5

env:
  matrix:
    secure: CINPTTJJKVBX6Nh/qiKNBLWQwwisHwuMa+TFXS/AMaWQsthpXxVNEtItD63stF9YdMzrJRcbqnC0XpeiAlKtmvQkftEEzNwcHA31IQzZXvWtIod2lvfNu4oP31SPyMNNqUX1yS8KhwyXLfC8G4ehPUW9m20DKvB1iy64o6xtW9o=

before_script:
  - composer install

script: bin/phpunit-randomizer --configuration phpunit.xml --coverage-text
